import requests
import json
import os
import common as cmn

"""
A script to download GDC RNA-seq or miRNA-seq files using the list generated by 
the accompanying FileLists.py
"""

# GDC API data endpoint URL (downloading files)
URL = cmn.BASE_URL+'data'


def make_dirs():
    """
    Create the directories needed by this script

    :return:
    """
    cmn.make_dir(cmn.DL_DIR)


def read_list_file(file_path):
    """
    Read a file list JSON file

    :param file_path: String path to the JSON file-list file
    :return:
    """


def main():
    # create required directories
    make_dirs()


if __name__ == "__main__":
    main()
