import requests
import json
import os
import common as cmn

"""
A script to download GDC RNA-seq or miRNA-seq files using the list generated by 
the accompanying FileLists.py
"""

# GDC API data endpoint URL (downloading files)
URL = 'https://api.gdc.cancer.gov/data'

# basic HTTP request header
HEADERS = {
    'Content-Type': 'application/json'
}

# absolute directory path to download files to (recommended if project is stored in space-sensitive
# location such as a cloud drive directory (Dropbox, OneDrive, etc...)
ABS_DL_DIR = os.path.abspath(os.path.join(os.path.expanduser('~'), 'Downloads', 'GDC_Downloads'))

# relative directory path to download files to
REL_DL_DIR = 'GDC_Downloads/'

# chosen downloads directory
DL_DIR = ABS_DL_DIR


def make_dirs():
    """
    Create the directories needed by this script

    :return:
    """
    cmn.make_dir(DL_DIR)


def main():
    # create required directories
    make_dirs()


if __name__ == "__main__":
    main()
