import requests
import json

"""
A script to download GDC RNA-seq or miRNA-seq files using the list generated by 
the accompanying FileLists.py
"""

# GDC API data endpoint URL (downloading files)
URL = 'https://api.gdc.cancer.gov/data'

# basic HTTP request header
HEADERS = {
    'Content-Type': 'application/json'
}

# default directory path to download files to
DL_DIR = ''
