import requests
import json
from os import path

"""
A script to download GDC RNA-seq or miRNA-seq files using the list generated by 
the accompanying FileLists.py
"""

# GDC API data endpoint URL (downloading files)
URL = 'https://api.gdc.cancer.gov/data'

# basic HTTP request header
HEADERS = {
    'Content-Type': 'application/json'
}

# absolute directory path to download files to (recommended if project is stored in space-sensitive
# location such as a cloud drive directory (Dropbox, OneDrive, etc...)
ABS_DL_DIR = path.join(path.expanduser('~'), 'Downloads', 'GDC_Downloads')

# relative directory path to download files to
REL_DL_DIR = 'GDC_Downloads/'
